package fr.uracraft.uramod.common;

import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import fr.uracraft.uramod.Items.Armors.ItemIridiumArmor;
import fr.uracraft.uramod.Items.Armors.ItemSilverArmor;
import fr.uracraft.uramod.Items.Armors.ItemTravelArmor;
import fr.uracraft.uramod.Items.Armors.ItemUraArmor;
import fr.uracraft.uramod.Items.*;
import fr.uracraft.uramod.Items.FurnaceUpgrades.*;
import fr.uracraft.uramod.Items.Tools.*;
import net.minecraft.item.Item;

public class UraItems {

    public static Item ura_ingot;
    public static Item ura_nugget;
    public static Item neodymium;
    public static Item iridium_ingot;
    public static Item iridium_nugget;
    public static Item silver_ingot;
    public static Item silver_nugget;
    public static Item ura_helmet;
    public static Item ura_chestplate;
    public static Item ura_leggings;
    public static Item ura_boots;
    public static Item silver_helmet;
    public static Item silver_chestplate;
    public static Item silver_leggings;
    public static Item silver_boots;
    public static Item ura_sword;
    public static Item ura_pickaxe;
    public static Item ura_shovel;
    public static Item ura_axe;
    public static Item ura_hoe;
    public static Item silver_sword;
    public static Item silver_pickaxe;
    public static Item silver_shovel;
    public static Item silver_axe;
    public static Item silver_hoe;
    public static Item hammer;
    public static Item magnifying_glass;
    public static Item claim_stick;
    public static Item ura_particle;
    public static Item silver_particle;
    public static Item neodymium_particle;
    public static Item silver_furnace_upgrade;
    public static Item ura_furnace_upgrade;
    public static Item neodymium_furnace_upgrade;
    public static Item iridium_furnace_upgrade;
    public static Item diamond_furnace_upgrade;
    public static Item iridium_helmet;
    public static Item iridium_chestplate;
    public static Item iridium_leggings;
    public static Item iridium_boots;
    public static Item iridium_pickaxe;
    public static Item iridium_sword;
    public static Item scuba_helmet;
    public static Item jump_chestplate;
    public static Item speed_leggings;
    public static Item farmer_boots;
    public static Item fake_water_bucket;
    public static Item fake_lava_bucket;
    public static Item glowstone_liquide_bucket;
    public static Item block_turner;
    public static Item silver_box_key;
    public static Item ura_box_key;
    public static Item neodymium_box_key;
    public static Item iridium_box_key;
    public static Item random_ore_item;
    public static Item dollar_one;
    public static Item dollar_five;
    public static Item dollar_ten;
    public static Item dollar_twenty;
    public static Item dollar_fifty;
    public static Item iridium_pickaxe_upgrade;
    public static Item iridium_excavator;
    public static Item hang_glider;

    public static void items(FMLPreInitializationEvent event){
        ura_ingot= new UraIngot();
        ura_nugget= new UraNugget();
        neodymium= new Neodymium();
        iridium_ingot= new IridiumIngot();
        iridium_nugget= new IridiumNugget();
        silver_ingot= new SilverIngot();
        silver_nugget= new SilverNugget();
        ura_helmet = new ItemUraArmor(UraArmors.ura_armor, 0).setUnlocalizedName("ura_helmet").setTextureName(UraMod.MODID + ":ura_helmet");
        ura_chestplate = new ItemUraArmor(UraArmors.ura_armor, 1).setUnlocalizedName("ura_chestplate").setTextureName(UraMod.MODID + ":ura_chestplate");
        ura_leggings = new ItemUraArmor(UraArmors.ura_armor, 2).setUnlocalizedName("ura_leggings").setTextureName(UraMod.MODID + ":ura_leggings");
        ura_boots = new ItemUraArmor(UraArmors.ura_armor, 3).setUnlocalizedName("ura_boots").setTextureName(UraMod.MODID + ":ura_boots");
        silver_helmet = new ItemSilverArmor(UraArmors.silver_armor, 0).setUnlocalizedName("silver_helmet").setTextureName(UraMod.MODID + ":silver_helmet");
        silver_chestplate = new ItemSilverArmor(UraArmors.silver_armor, 1).setUnlocalizedName("silver_chestplate").setTextureName(UraMod.MODID + ":silver_chestplate");
        silver_leggings = new ItemSilverArmor(UraArmors.silver_armor, 2).setUnlocalizedName("silver_leggings").setTextureName(UraMod.MODID + ":silver_leggings");
        silver_boots = new ItemSilverArmor(UraArmors.silver_armor, 3).setUnlocalizedName("silver_boots").setTextureName(UraMod.MODID + ":silver_boots");
        iridium_helmet = new ItemIridiumArmor(UraArmors.iridium_armor, 0).setUnlocalizedName("iridium_helmet").setTextureName(UraMod.MODID + ":iridium_helmet");
        iridium_chestplate = new ItemIridiumArmor(UraArmors.iridium_armor, 1).setUnlocalizedName("iridium_chestplate").setTextureName(UraMod.MODID + ":iridium_chestplate");
        iridium_leggings = new ItemIridiumArmor(UraArmors.iridium_armor, 2).setUnlocalizedName("iridium_leggings").setTextureName(UraMod.MODID + ":iridium_leggings");
        iridium_boots = new ItemIridiumArmor(UraArmors.iridium_armor, 3).setUnlocalizedName("iridium_boots").setTextureName(UraMod.MODID + ":iridium_boots");
        scuba_helmet = new ItemTravelArmor(UraArmors.travel_armor, 0).setUnlocalizedName("scuba_helmet").setTextureName(UraMod.MODID + ":scuba_helmet");
        jump_chestplate = new ItemTravelArmor(UraArmors.travel_armor, 1).setUnlocalizedName("jump_chestplate").setTextureName(UraMod.MODID + ":jump_chestplate");
        speed_leggings = new ItemTravelArmor(UraArmors.travel_armor, 2).setUnlocalizedName("speed_leggings").setTextureName(UraMod.MODID + ":speed_leggings");
        farmer_boots = new ItemTravelArmor(UraArmors.travel_armor, 3).setUnlocalizedName("farmer_boots").setTextureName(UraMod.MODID + ":farmer_boots");
        iridium_sword = new ItemSword(UraTools.iridium_tools).setUnlocalizedName("iridium_sword").setTextureName(UraMod.MODID + ":iridium_sword");
        iridium_pickaxe = new ItemPickaxe(UraTools.iridium_tools).setUnlocalizedName("iridium_pickaxe").setTextureName(UraMod.MODID + ":iridium_pickaxe");
        ura_sword = new ItemSword(UraTools.ura_tools).setUnlocalizedName("ura_sword").setTextureName(UraMod.MODID + ":ura_sword");
        ura_pickaxe = new ItemPickaxe(UraTools.ura_tools).setUnlocalizedName("ura_pickaxe").setTextureName(UraMod.MODID + ":ura_pickaxe");
        ura_shovel = new ItemShovel(UraTools.ura_tools).setUnlocalizedName("ura_shovel").setTextureName(UraMod.MODID + ":ura_shovel");
        ura_axe = new ItemAxe(UraTools.ura_tools).setUnlocalizedName("ura_axe").setTextureName(UraMod.MODID + ":ura_axe");
        ura_hoe = new ItemHoe(UraTools.ura_tools).setUnlocalizedName("ura_hoe").setTextureName(UraMod.MODID + ":ura_hoe");
        silver_sword = new ItemSword(UraTools.silver_tools).setUnlocalizedName("silver_sword").setTextureName(UraMod.MODID + ":silver_sword");
        silver_pickaxe = new ItemPickaxe(UraTools.silver_tools).setUnlocalizedName("silver_pickaxe").setTextureName(UraMod.MODID + ":silver_pickaxe");
        silver_shovel = new ItemShovel(UraTools.silver_tools).setUnlocalizedName("silver_shovel").setTextureName(UraMod.MODID + ":silver_shovel");
        silver_axe = new ItemAxe(UraTools.silver_tools).setUnlocalizedName("silver_axe").setTextureName(UraMod.MODID + ":silver_axe");
        silver_hoe = new ItemHoe(UraTools.silver_tools).setUnlocalizedName("silver_hoe").setTextureName(UraMod.MODID + ":silver_hoe");
        hammer = new ItemHammer(UraTools.hammer).setUnlocalizedName("hammer").setTextureName(UraMod.MODID + ":hammer");
        iridium_excavator = new ItemExcavator(UraTools.iridium_excavator).setUnlocalizedName("iridium_excavator").setTextureName(UraMod.MODID + ":iridium_excavator");
        magnifying_glass= new MagnifyingGlass();
        claim_stick= new ClaimStick();
        ura_particle= new UraParticle();
        silver_particle= new SilverParticle();
        neodymium_particle= new NeodymiumParticle();
        silver_furnace_upgrade= new SilverFurnaceUpgrade();
        ura_furnace_upgrade= new UraFurnaceUpgrade();
        neodymium_furnace_upgrade= new NeodymiumFurnaceUpgrade();
        iridium_furnace_upgrade= new IridiumFurnaceUpgrade();
        diamond_furnace_upgrade= new DiamondFurnaceUpgrade();
        fake_water_bucket = new FakeWaterBucket();
        fake_lava_bucket = new FakeLavaBucket();
        glowstone_liquide_bucket = new GlowstoneLiquideBucket();
        block_turner = new BlockTurner();
        silver_box_key = new GenericBoxKey("silver");
        ura_box_key = new GenericBoxKey("ura");
        neodymium_box_key = new GenericBoxKey("neodymium");
        iridium_box_key = new GenericBoxKey("iridium");
        random_ore_item = new RandomOreItem();
        dollar_one = new Dollar("one");
        dollar_five = new Dollar("five");
        dollar_ten = new Dollar("ten");
        dollar_twenty = new Dollar("twenty");
        dollar_fifty = new Dollar("fifty");
        iridium_pickaxe_upgrade = new IridiumPickaxeUpgrade();
        hang_glider = new HangGlider();

        GameRegistry.registerItem(ura_ingot,"ura_ingot");
        GameRegistry.registerItem(ura_nugget,"ura_nugget");
        GameRegistry.registerItem(neodymium,"neodymium");
        GameRegistry.registerItem(iridium_ingot,"iridium_ingot");
        GameRegistry.registerItem(iridium_nugget,"iridium_nugget");
        GameRegistry.registerItem(silver_ingot,"silver_ingot");
        GameRegistry.registerItem(silver_nugget,"silver_nugget");
        GameRegistry.registerItem(ura_helmet,"ura_helmet");
        GameRegistry.registerItem(ura_chestplate,"ura_chestplate");
        GameRegistry.registerItem(ura_leggings,"ura_leggings");
        GameRegistry.registerItem(ura_boots,"ura_boots");
        GameRegistry.registerItem(silver_helmet,"silver_helmet");
        GameRegistry.registerItem(silver_chestplate,"silver_chestplate");
        GameRegistry.registerItem(silver_leggings,"silver_leggings");
        GameRegistry.registerItem(silver_boots,"silver_boots");
        GameRegistry.registerItem(ura_sword,"ura_sword");
        GameRegistry.registerItem(ura_pickaxe,"ura_pickaxe");
        GameRegistry.registerItem(ura_shovel,"ura_shovel");
        GameRegistry.registerItem(ura_axe,"ura_axe");
        GameRegistry.registerItem(ura_hoe,"ura_hoe");
        GameRegistry.registerItem(silver_sword,"silver_sword");
        GameRegistry.registerItem(silver_pickaxe,"silver_pickaxe");
        GameRegistry.registerItem(silver_shovel,"silver_shovel");
        GameRegistry.registerItem(silver_axe,"silver_axe");
        GameRegistry.registerItem(silver_hoe,"silver_hoe");
        GameRegistry.registerItem(hammer,"hammer");
        GameRegistry.registerItem(magnifying_glass,"magnifying_glass");
        GameRegistry.registerItem(claim_stick,"claim_stick");
        GameRegistry.registerItem(ura_particle,"ura_particle");
        GameRegistry.registerItem(silver_particle,"silver_particle");
        GameRegistry.registerItem(neodymium_particle,"neodymium_particle");
        GameRegistry.registerItem(silver_furnace_upgrade,"silver_furnace_upgrade");
        GameRegistry.registerItem(ura_furnace_upgrade,"ura_furnace_upgrade");
        GameRegistry.registerItem(neodymium_furnace_upgrade,"neodymium_furnace_upgrade");
        GameRegistry.registerItem(iridium_furnace_upgrade,"iridium_furnace_upgrade");
        GameRegistry.registerItem(diamond_furnace_upgrade,"diamond_furnace_upgrade");
        GameRegistry.registerItem(iridium_helmet,"iridium_helmet");
        GameRegistry.registerItem(iridium_chestplate,"iridium_chestplate");
        GameRegistry.registerItem(iridium_leggings,"iridium_leggings");
        GameRegistry.registerItem(iridium_boots,"iridium_boots");
        GameRegistry.registerItem(iridium_pickaxe,"iridium_pickaxe");
        GameRegistry.registerItem(iridium_sword,"iridium_sword");
        GameRegistry.registerItem(scuba_helmet,"scuba_helmet");
        GameRegistry.registerItem(jump_chestplate,"jump_chestplate");
        GameRegistry.registerItem(speed_leggings,"speed_leggings");
        GameRegistry.registerItem(farmer_boots,"farmer_boots");
        GameRegistry.registerItem(fake_water_bucket,"fake_water_bucket");
        GameRegistry.registerItem(fake_lava_bucket,"fake_lava_bucket");
        GameRegistry.registerItem(glowstone_liquide_bucket,"glowstone_liquide_bucket");
        GameRegistry.registerItem(block_turner,"block_turner");
        GameRegistry.registerItem(silver_box_key,"silver_box_key");
        GameRegistry.registerItem(ura_box_key,"ura_box_key");
        GameRegistry.registerItem(neodymium_box_key,"neodymium_box_key");
        GameRegistry.registerItem(iridium_box_key,"iridium_box_key");
        GameRegistry.registerItem(random_ore_item,"random_ore_item");
        GameRegistry.registerItem(dollar_one,"dollar_one");
        GameRegistry.registerItem(dollar_five,"dollar_five");
        GameRegistry.registerItem(dollar_ten,"dollar_ten");
        GameRegistry.registerItem(dollar_twenty,"dollar_twenty");
        GameRegistry.registerItem(dollar_fifty,"dollar_fifty");
        GameRegistry.registerItem(iridium_pickaxe_upgrade,"iridium_pickaxe_upgrade");
        GameRegistry.registerItem(iridium_excavator,"iridium_excavator");
        GameRegistry.registerItem(hang_glider,"hang_glider");
    }
}